# fly.toml app configuration file generated for load-tester on 2025-03-28T16:06:29+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'load-tester'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  REDIS_HOST='redis-17996.c37407.asia-seast1-mz.gcp.cloud.rlrcp.com
  REDIS_PORT=17996
  REDIS_PASSWORD='HfeBoUt7osO9ijZnK9JoxAOLHnhrVD8x'
  REDIS_DB=0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'

[deploy]
  strategy = "immediate"
  release_command = ""

[build.args]
  VCS_BRANCH = "main"
